---
title: "figures"
author: "Tim Ohlert"
date: "11/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#load libraries
```{r}
library(lmerTest)
library(visreg)
library(MuMIn)
library(ggeffects)
library(ggthemes)
library(tidyverse)
library(viridis)
```


# load data

```{r}
hv_climate_allsites <- read_csv("hv_climate-11.25.20.csv")
```

```{r}
hv_climate <- subset(hv_climate_allsites, 
                      site != "crust_creosote" &
                      site != "crust_grass" &
                      site != "crust_PJ" &
                      site != "grid_black" &
                      site != "grid_blue" &
                      site != "grid_creosote" &
                      site != "iso_web" &
                      site != "tower_west"
                      )
```




# alpha diversity

## model comparison

```{r}
alphamod.1 <- lmer(log_alpha ~ SPEI.comp + (1|year/site), data = hv_climate) # for a location, are SPEI changes through time associated with alpha?
alphamod.site <- lmer(log_alpha~SPEI.comp*site + (1|year) + (1|replicate), data = hv_climate) # within-site diversity change. At whih sites are SPEI changes through time related to alpha?
 
alphamod.2 <- lmer(log_alpha ~ SPEI.comp + I(SPEI.comp^2) + (1|year/site), data = hv_climate)
alphamod.3 <- lmer(log_alpha ~ SPEI.comp  + I(SPEI.comp^2) + I(SPEI.comp^3) + (1|year/site), data = hv_climate)
alphamod.4 <- lmer(log_alpha ~ SPEI.comp + I(SPEI.comp^2) + I(SPEI.comp^3) + I(SPEI.comp^4) + (1|year/site), data = hv_climate)
alphamod.5 <- lmer(log_alpha ~ SPEI.comp + I(SPEI.comp^2) + I(SPEI.comp^3) + I(SPEI.comp^4) + I(SPEI.comp^5) + (1|year/site), data = hv_climate)

AICc(alphamod.1, alphamod.2, alphamod.3, alphamod.4, alphamod.5)

```

```{r}
summary(alphamod.1)
r.squaredGLMM(alphamod.1)
```


```{r}
summary(alphamod.site)
```







## graph
```{r}
hist(hv_climate$alpha)
hist(hv_climate$log_alpha)
```

```{r}
x <- ggpredict(alphamod.1, c("SPEI.comp"))
plot(x, ci=FALSE)+
  geom_ribbon(aes(ymin=predicted-std.error,ymax=predicted+std.error), alpha =.5)+
  geom_point(data=hv_climate, aes(x=SPEI.comp,y=log_alpha, colour = site, alpha = .05))+
  scale_color_viridis(discrete = TRUE, option = "D")+
  theme_base()
```


```{r}
ggplot(hv_climate, aes(SPEI.comp,log_alpha))+
  facet_wrap(~site)+
  geom_smooth(method = "lm")+
  geom_point(data=hv_climate, aes(x=SPEI.comp,y=log_alpha, colour = site, alpha = .05))+
  scale_color_viridis(discrete = TRUE, option = "D")+
  theme(legend.position = "none")#+
  #theme_base()
```






# evenness

## model comparison

```{r}
evenmod.1 <- lmer(evenness ~ SPEI.comp + (1|year/site), data = hv_climate)
evenmod.site <- lmer(evenness~ SPEI.comp*site + (1|year) + (1|replicate), data = hv_climate)


evenmod.2 <- lmer(evenness ~ SPEI.comp + I(SPEI.comp^2) + (1|year/site), data = hv_climate)
evenmod.3 <- lmer(evenness ~ SPEI.comp  + I(SPEI.comp^2) + I(SPEI.comp^3) + (1|year/site), data = hv_climate)
evenmod.4 <- lmer(evenness ~ SPEI.comp + I(SPEI.comp^2) + I(SPEI.comp^3) + I(SPEI.comp^4) + (1|year/site), data = hv_climate)
evenmod.5 <- lmer(evenness ~ SPEI.comp + I(SPEI.comp^2) + I(SPEI.comp^3) + I(SPEI.comp^4) + I(SPEI.comp^5) + (1|year/site), data = hv_climate)

AICc(evenmod.1, evenmod.2, evenmod.3, evenmod.4, evenmod.5)
```


```{r}
summary(evenmod.1)
r.squaredGLMM(evenmod.1)

summary(evenmod.site)
```


## graph

```{r}
x <- ggpredict(evenmod.1, c("SPEI.comp"))
plot(x, ci=FALSE)+
  geom_ribbon(aes(ymin=predicted-std.error,ymax=predicted+std.error), alpha =.5)+
  geom_point(data=hv_climate, aes(x=SPEI.comp,y=evenness), alpha = .05)+
  theme_base()
```


```{r}
ggplot(hv_climate, aes(SPEI.comp,evenness))+
  facet_wrap(~site)+
  geom_smooth(method = "lm")+
  geom_point(data=hv_climate, aes(x=SPEI.comp,y=evenness, colour = site))+
  scale_color_viridis(discrete = TRUE, option = "D")+
   theme(legend.position = "none")#+
  #theme_base()
```



# dispersion

## model comparison

```{r}
dispmod.1 <- lmer(dispersion ~ SPEI.comp + (1|year/site), data = hv_climate)
dispmod.site <- lmer(dispersion~ SPEI.comp*site + (1|year) + (1|replicate), data = hv_climate)

dispmod.2 <- lmer(dispersion ~ SPEI.comp + I(SPEI.comp^2) + (1|year/site), data = hv_climate)
dispmod.3 <- lmer(dispersion ~ SPEI.comp  + I(SPEI.comp^2) + I(SPEI.comp^3) + (1|year/site), data = hv_climate)
dispmod.4 <- lmer(dispersion ~ SPEI.comp + I(SPEI.comp^2) + I(SPEI.comp^3) + I(SPEI.comp^4) + (1|year/site), data = hv_climate)
dispmod.5 <- lmer(dispersion ~ SPEI.comp + I(SPEI.comp^2) + I(SPEI.comp^3) + I(SPEI.comp^4) + I(SPEI.comp^5) + (1|year/site), data = hv_climate)

AICc(dispmod.1, dispmod.2, dispmod.3, dispmod.4, dispmod.5)
```

```{r}
summary(dispmod.1)
r.squaredGLMM(dispmod.1)
summary(dispmod.site)
```


## graph

```{r}
x <- ggpredict(dispmod.1, c("SPEI.comp"))
plot(x, ci=FALSE)+
  geom_ribbon(aes(ymin=predicted-std.error,ymax=predicted+std.error), alpha =.5)+
  geom_point(data=hv_climate, aes(x=SPEI.comp,y=dispersion), alpha = .05)+
  theme_base()
```

```{r}
ggplot(hv_climate, aes(SPEI.comp,dispersion))+
  facet_wrap(~site)+
  geom_smooth(method = "lm")+
  geom_point(data=hv_climate, aes(x=SPEI.comp,y=dispersion, colour = site), alpha = .05)+
  scale_color_viridis(discrete = TRUE, option = "D")+
   theme(legend.position = "none")#+
  #theme_base()
```




```{r}
hist(hv_climate$dispersion)
```




# change between years

                       
## make delta metrics
```{r}
hv_climate_delta <- hv_climate %>% 
  arrange(replicate, desc(year)) %>% 
  mutate(alpha.delta = c(diff(alpha), NA)) %>%
  mutate(logalpha.delta = c(diff(log_alpha), NA)) %>%
  mutate(evenness.delta = c(diff(evenness), NA)) %>%
  mutate(dispersion.delta = c(diff(dispersion), NA)) %>% 
  mutate(spei.delta = c(diff(SPEI.comp), NA)) %>%
  na.omit



dummy <- hv_climate

dummy$year <- hv_climate$year - 1

dummy <- dummy %>% 
  rename(
    alpha.2 = alpha,
    log_alpha.2 = log_alpha,
    evenness.2 = evenness,
    dispersion.2 = dispersion,
    SPEI.comp.2 = SPEI.comp
        )


dummy <- dummy[,c("replicate","year", "alpha.2", "log_alpha.2", "evenness.2", "dispersion.2", "SPEI.comp.2")]


hv_climate_prevyear <- merge(hv_climate, dummy, by = c("replicate", "year"))



hv_climate_prevyear$alpha_delta <- hv_climate_prevyear$alpha - hv_climate_prevyear$alpha.2
hv_climate_prevyear$log_alpha_delta <- hv_climate_prevyear$log_alpha - hv_climate_prevyear$log_alpha.2
hv_climate_prevyear$evenness_delta <- hv_climate_prevyear$evenness - hv_climate_prevyear$evenness.2
hv_climate_prevyear$dispersion_delta <- hv_climate_prevyear$dispersion - hv_climate_prevyear$dispersion.2
hv_climate_prevyear$SPEI_delta <- hv_climate_prevyear$SPEI.comp - hv_climate_prevyear$SPEI.comp.2


hv_climate_delta <- hv_climate_prevyear[,c("replicate", "year", "site", "alpha_delta", "log_alpha_delta", "evenness_delta", "dispersion_delta", "SPEI_delta")]


```



## model alpha change
```{r}
alphamod.1 <- lmer(log_alpha_delta ~ SPEI_delta + (1|year/site), data = hv_climate_delta) # for a location, are SPEI changes through time associated with alpha?
alphamod.site <- lmer(log_alpha_delta~SPEI_delta*site + (1|year) + (1|replicate), data = hv_climate_delta) # within-site diversity change. At whih sites are SPEI changes through time related to alpha?
 
alphamod.2 <- lmer(log_alpha_delta ~ SPEI_delta + I(SPEI_delta^2) + (1|year/site), data = hv_climate_delta)
alphamod.3 <- lmer(log_alpha_delta ~ SPEI_delta  + I(SPEI_delta^2) + I(SPEI_delta^3) + (1|year/site), data = hv_climate_delta)
alphamod.4 <- lmer(log_alpha_delta ~ SPEI_delta + I(SPEI_delta^2) + I(SPEI_delta^3) + I(SPEI_delta^4) + (1|year/site), data = hv_climate_delta)
alphamod.5 <- lmer(log_alpha_delta ~ SPEI_delta + I(SPEI_delta^2) + I(SPEI_delta^3) + I(SPEI_delta^4) + I(SPEI_delta^5) + (1|year/site), data = hv_climate_delta)

AICc(alphamod.1, alphamod.2, alphamod.3, alphamod.4, alphamod.5)

```

```{r}
summary(alphamod.1)
r.squaredGLMM(alphamod.1)
```


```{r}
summary(alphamod.site)
```


## graph alpha change

```{r}
x <- ggpredict(alphamod.1, c("SPEI_delta"))
plot(x, ci=FALSE)+
  geom_ribbon(aes(ymin=predicted-std.error,ymax=predicted+std.error), alpha =.5)+
  geom_point(data=hv_climate_delta, aes(x=SPEI_delta,y=log_alpha_delta, colour = site, alpha = .05))+
  scale_color_viridis(discrete = TRUE, option = "D")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  theme_base()
```







```{r}
ggplot(hv_climate_delta, aes(SPEI_delta,log_alpha_delta))+
  facet_wrap(~site)+
  geom_smooth(method = "lm")+
  geom_point(data=hv_climate_delta, aes(x=SPEI_delta,y=log_alpha_delta, colour = site, alpha = .05))+
  scale_color_viridis(discrete = TRUE, option = "D")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  theme(legend.position = "none")#+
  #theme_base()
```






## model evenness change
```{r}
evenness.1 <- lmer(evenness_delta ~ SPEI_delta + (1|year/site), data = hv_climate_delta) 
evenness.site <- lmer(evenness_delta~SPEI_delta*site + (1|year) + (1|replicate), data = hv_climate_delta) 
 
evenness.2 <- lmer(evenness_delta ~ SPEI_delta + I(SPEI_delta^2) + (1|year/site), data = hv_climate_delta)
evenness.3 <- lmer(evenness_delta ~ SPEI_delta  + I(SPEI_delta^2) + I(SPEI_delta^3) + (1|year/site), data = hv_climate_delta)
evenness.4 <- lmer(evenness_delta ~ SPEI_delta + I(SPEI_delta^2) + I(SPEI_delta^3) + I(SPEI_delta^4) + (1|year/site), data = hv_climate_delta)
evenness.5 <- lmer(evenness_delta ~ SPEI_delta + I(SPEI_delta^2) + I(SPEI_delta^3) + I(SPEI_delta^4) + I(SPEI_delta^5) + (1|year/site), data = hv_climate_delta)

AICc(evenness.1, evenness.2, evenness.3, evenness.4, evenness.5)

```

```{r}
summary(evenness.1)
r.squaredGLMM(evenness.1)
```


```{r}
summary(evenness.site)
```


## graph evenness change

```{r}
x <- ggpredict(evenness.1, c("SPEI_delta"))
plot(x, ci=FALSE)+
  geom_ribbon(aes(ymin=predicted-std.error,ymax=predicted+std.error), alpha =.5)+
  geom_point(data=hv_climate_delta, aes(x=SPEI_delta,y=evenness_delta, colour = site, alpha = .05))+
  scale_color_viridis(discrete = TRUE, option = "D")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  theme_base()
```







```{r}
ggplot(hv_climate_delta, aes(SPEI_delta,evenness_delta))+
  facet_wrap(~site)+
  geom_smooth(method = "lm")+
  geom_point(data=hv_climate_delta, aes(x=SPEI_delta,y=evenness_delta, colour = site, alpha = .05))+
  scale_color_viridis(discrete = TRUE, option = "D")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  theme(legend.position = "none")#+
  #theme_base()
```





## model dispersion change
```{r}
dispersion.1 <- lmer(dispersion_delta ~ SPEI_delta + (1|year/site), data = hv_climate_delta) 
dispersion.site <- lmer(dispersion_delta~SPEI_delta*site + (1|year) + (1|replicate), data = hv_climate_delta) 
 
dispersion.2 <- lmer(dispersion_delta ~ SPEI_delta + I(SPEI_delta^2) + (1|year/site), data = hv_climate_delta)
dispersion.3 <- lmer(dispersion_delta ~ SPEI_delta  + I(SPEI_delta^2) + I(SPEI_delta^3) + (1|year/site), data = hv_climate_delta)
dispersion.4 <- lmer(dispersion_delta ~ SPEI_delta + I(SPEI_delta^2) + I(SPEI_delta^3) + I(SPEI_delta^4) + (1|year/site), data = hv_climate_delta)
dispersion.5 <- lmer(dispersion_delta ~ SPEI_delta + I(SPEI_delta^2) + I(SPEI_delta^3) + I(SPEI_delta^4) + I(SPEI_delta^5) + (1|year/site), data = hv_climate_delta)

AICc(dispersion.1, dispersion.2, dispersion.3, dispersion.4, dispersion.5)

```

```{r}
summary(dispersion.1)
r.squaredGLMM(dispersion.1)
```


```{r}
summary(dispersion.site)
```


## graph evenness change

```{r}
x <- ggpredict(dispersion.1, c("SPEI_delta"))
plot(x, ci=FALSE)+
  geom_ribbon(aes(ymin=predicted-std.error,ymax=predicted+std.error), alpha =.5)+
  geom_point(data=hv_climate_delta, aes(x=SPEI_delta,y=dispersion_delta, colour = site, alpha = .05))+
  scale_color_viridis(discrete = TRUE, option = "D")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  theme_base()
```







```{r}
ggplot(hv_climate_delta, aes(SPEI_delta,evenness_delta))+
  facet_wrap(~site)+
  geom_smooth(method = "lm")+
  geom_point(data=hv_climate_delta, aes(x=SPEI_delta,y=dispersion_delta, colour = site, alpha = .05))+
  scale_color_viridis(discrete = TRUE, option = "D")+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  theme(legend.position = "none")#+
  #theme_base()
```
















